### ISSUE TITLE
Div height - #js-bootstrap-offcanvas

### ISSUE THREAD

**Issue by SiteOp** [alihaddadkar/bootstrap-off-canvas-menu#6]
Hello,
The iPad version of the navigation is faulty . 
Once selecting a navigation point changes the Div container
# Js - bootstrap offcanvas its height .

![ipad2](https://cloud.githubusercontent.com/assets/2822837/15890890/27f14394-2d72-11e6-9919-071cd8f311d7.jpg)

![ipad1](https://cloud.githubusercontent.com/assets/2822837/15890892/2a3d256e-2d72-11e6-9582-72d8d73cd98f.jpg)

**Comment by alihaddadkar** [comment]
Hello.
Thanks for reporting.

**Comment by alihaddadkar** [comment]
Solved

**Comment by SiteOp** [comment]
hello,
thanks for the work. Representation on iPad, however, still immediately.

**Comment by alihaddadkar** [comment]
Now, you have a problem?

**Comment by SiteOp** [comment]
Hello, have you to check the possibility the representation on iPad? Issue still how with the pictures on top.

**Comment by alihaddadkar** [comment]
Unfortunately I don't have a ipad. I can't test.
Please take screenshots of the problem.
thanks

**Comment by SiteOp** [comment]
hello,
thanks for the feedback. Screenshot from iPad see above.
I have tested once the following:
@media  (min-width: 769px)   {
    #js-bootstrap-offcanvas {height: $navbar-height!important;}
    }

With me it functions.
